### ISSUE TITLE
Not WOrking ( 

### ISSUE THREAD

**Issue by IIayk122** [toirl/cointrader#33]
* Cointrader version: 0.5.
* Python version: 2.7.12
* Operating System: Mint

### Description

I installed the program according to the instructions, created the config, entered Api and Secret, but when I try to execute any command, I get an error. Listing attached.

### What I Did

di1 cointrader # cointrader balance
Traceback (most recent call last):
  File "/usr/local/bin/cointrader", line 11, in <module>
    load_entry_point('cointrader==0.5.0', 'console_scripts', 'cointrader')()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cointrader-0.5.0-py2.7.egg/cointrader/cli.py", line 36, in main
    ctx.exchange = Poloniex(config)
  File "/usr/local/lib/python2.7/dist-packages/cointrader-0.5.0-py2.7.egg/cointrader/exchange.py", line 299, in __init__
    Exchange.__init__(self, config, api)
  File "/usr/local/lib/python2.7/dist-packages/cointrader-0.5.0-py2.7.egg/cointrader/exchange.py", line 225, in __init__
    balance = self._api.balance()
  File "/usr/local/lib/python2.7/dist-packages/cointrader-0.5.0-py2.7.egg/cointrader/exchanges/poloniex.py", line 237, in balance
    result[currency]["quantity"] = float(tmp[currency]["available"])
TypeError: string indices must be integers
``

**Comment by toirl** [comment]
Thanks for the report. I will look into it later this day.

**Comment by bahelit** [comment]
That's the error that was reported when I attempted to run the program without replacing the API key and secret within the config file. "string indices must be integers"

**Comment by toirl** [comment]
@bahelit Thanks for the hint :+1:  I've added further checks on reported errors from the API and now return a userfriendly error message in this case.

@IIayk122 Does this solve your problem?
